INSERT INTO Employees (Name, DepartmentId)
VALUES
('Ahmed Tohamy', 1),
('Omar Selim', 1),
('Mohamed Tohamy', 1),
('Ali Selim', 2),
('Youssef Tohamy', 2),
('Khaled Selim', 2),
('Hassan Tohamy', 3),
('Mahmoud Selim', 3),
('Ibrahim Tohamy', 3),
('Mostafa Selim', 4),
('Adel Tohamy', 4),
('Saeed Selim', 4),
('Amr Tohamy', 5),
('Tamer Selim', 5),
('Walid Tohamy', 5),
('Karim Selim', 6),
('Nour Tohamy', 6),
('Ziad Selim', 6),
('Ehab Tohamy', 7),
('Sherif Selim', 7),
('Tarek Tohamy', 7),
('Mina Selim', 8),
('Gamal Tohamy', 8),
('Hany Selim', 8),

-- زيادة تنوع
('Ahmed Tohamy Jr', 1),
('Omar Selim Jr', 1),
('Mohamed Tohamy Jr', 2),
('Ali Selim Jr', 2),
('Youssef Tohamy Jr', 3),
('Khaled Selim Jr', 3),
('Hassan Tohamy Jr', 4),
('Mahmoud Selim Jr', 4),
('Ibrahim Tohamy Jr', 5),
('Mostafa Selim Jr', 5),
('Adel Tohamy Jr', 6),
('Saeed Selim Jr', 6),
('Amr Tohamy Jr', 7),
('Tamer Selim Jr', 7),
('Walid Tohamy Jr', 8),
('Karim Selim Jr', 8);